## Accessing the items using indexing and slicing

In [1]:
list1 = [1,2,3,4,5,6]
list1[2]

3

In [2]:
list1[2:4]

[3, 4]

In [4]:
list1[4:2:-1]

[5, 4]

In [ ]:
# pip install numpy
# pip install pandas

In [5]:
import numpy as np

In [7]:
array1 = np.array([1,2,3,4,5,6,7,8])

array1[4]

5

In [8]:
array1[4:]

array([5, 6, 7, 8])

In [9]:
array1[4:1:-1]

array([5, 4, 3])

In [10]:
array1[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

### 2D Array

In [11]:
array2 = np.array([[1,2,3],[10,20,30],[100,200,300]])
array2.ndim

2

In [12]:
list2 = [[1,2,3],[10,20,30],[100,200,300]]
list2[1][-1]

30

In [13]:
array2[1][-1]

30

In [14]:
array2[2][2]

300

In [15]:
print(array2)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [17]:
array2[0,2]

3

In [ ]:
#array2[m,n] m indicates mth row element and n indicate nth column element
#array2[m:,n:] this will give us all rows starting from mth row and all columns starting from nth column
#array2[row,column]

In [21]:
array2[1,2]

30

In [22]:
array2[2,2]

300

In [24]:
array2[2,1]

200

In [25]:
array2[0,0]

1

In [27]:
print(array2)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [28]:
array2[0:2,0]

array([ 1, 10])

In [29]:
array2[0:,0]

array([  1,  10, 100])

In [30]:
array2[0:,1]

array([  2,  20, 200])

In [31]:
array2[0:,2]

array([  3,  30, 300])

In [32]:
array2[0,1]

2

In [34]:
array2[0,0:]

array([1, 2, 3])

In [35]:
array2[1,0:]

array([10, 20, 30])

In [36]:
array2[2,0:]

array([100, 200, 300])

In [37]:
print(array2)

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]]


In [38]:
array2[1:,1:]

array([[ 20,  30],
       [200, 300]])

In [39]:
array2[0:2,0:2]

array([[ 1,  2],
       [10, 20]])

In [41]:
array2[:,2]

array([  3,  30, 300])

In [42]:
array2[0:,0]

array([  1,  10, 100])

In [46]:
array2[1,:]

array([10, 20, 30])

In [45]:
array2[1,1:]

array([20, 30])

In [44]:
array2[1]

array([10, 20, 30])