## Numpy Logarithms

In [1]:
import numpy as np

In [ ]:
1. np.log()
2. np.log2()
3. np.log10()

### np.log()

In [ ]:
Natural Log (to the base e)

In [2]:
array1 = np.array(20)
array1_log_e = np.log(array1)
print(array1_log_e)

2.995732273553991


In [3]:
array1 = np.random.randint(10,99,10)
print("Original Array: \n", array1, end ="\n\n")
array1_log_e = np.log(array1)
print("Array after taking Natural Log: \n",array1_log_e)

Original Array: 
 [31 71 77 12 98 25 72 11 77 23]

Array after taking Natural Log: 
 [3.4339872  4.26267988 4.34380542 2.48490665 4.58496748 3.21887582
 4.27666612 2.39789527 4.34380542 3.13549422]


### np.log2()

In [4]:
array1 = np.random.randint(10,99,10)
print("Original Array: \n", array1, end ="\n\n")
array1_log_e = np.log2(array1)
print("Array after taking Natural Log: \n",array1_log_e)

Original Array: 
 [46 22 64 95 44 50 61 46 11 75]

Array after taking Natural Log: 
 [5.52356196 4.45943162 6.         6.56985561 5.45943162 5.64385619
 5.93073734 5.52356196 3.45943162 6.22881869]


### np.log10()

In [5]:
array1 = np.random.randint(10,99,10)
print("Original Array: \n", array1, end ="\n\n")
array1_log_e = np.log10(array1)
print("Array after taking Natural Log: \n",array1_log_e)

Original Array: 
 [85 89 61 50 79 12 25 47 20 89]

Array after taking Natural Log: 
 [1.92941893 1.94939001 1.78532984 1.69897    1.89762709 1.07918125
 1.39794001 1.67209786 1.30103    1.94939001]
