# Mathematical Operations

### np.floor()

In [1]:
import numpy as np

In [2]:
array1 = np.array([2.3445,5.6745,9.454,8.343,4.3432])

print("The original Array: ", array1)

array2 = np.floor(array1)

print("The array with floored value: ", array2)

The original Array:  [2.3445 5.6745 9.454  8.343  4.3432]
The array with floored value:  [2. 5. 9. 8. 4.]


In [3]:
array1 = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

print("The original Array: ", array1)

array2 = np.floor(array1)

print("The array with floored value: ", array2)

The original Array:  [-1.7 -1.5 -0.2  0.2  1.5  1.7  2. ]
The array with floored value:  [-2. -2. -1.  0.  1.  1.  2.]


### np.ceil

In [4]:
array1 = np.array([2.3445,5.6745,9.454,8.343,4.3432])

print("The original Array: ", array1)

array2 = np.ceil(array1)

print("The array with ceiled value: ", array2)

The original Array:  [2.3445 5.6745 9.454  8.343  4.3432]
The array with floored value:  [ 3.  6. 10.  9.  5.]


In [6]:
array1 = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

print("The original Array: ", array1)

array2 = np.ceil(array1)

print("The array with ceiled value: ", array2)

The original Array:  [-1.7 -1.5 -0.2  0.2  1.5  1.7  2. ]
The array with floored value:  [-1. -1. -0.  1.  2.  2.  2.]


### np.around()

In [7]:
array1 = np.array([2.3445,5.6745,9.454,8.343,4.3432])

print("The original Array: ", array1)

array2 = np.around(array1)  ## Will return an array with closest full value

print("The array with roundoff value: ", array2)

The original Array:  [2.3445 5.6745 9.454  8.343  4.3432]
The array with floored value:  [2. 6. 9. 8. 4.]


In [9]:
array1 = np.array([2.3445,5.6766,9.4548,8.3479,4.3482])

print("The original Array: ", array1)

array2 = np.around(array1,2)  ## Will return an array with closest full value

print("The array with aroundoff value: ", array2)

The original Array:  [2.3445 5.6766 9.4548 8.3479 4.3482]
The array with floored value:  [2.34 5.68 9.45 8.35 4.35]


### np.sqrt

In [15]:
array1 = np.random.randint(10,50,size = 10)

print("The original Array: ", array1)

array2 = np.sqrt(array1)  
print()
print("The array with Square Root Value: ", array2)

array3 = np.around(array2,4)
print()
print("The array with rounded off squareroot values:", array3)

The original Array:  [23 41 46 45 22 22 36 31 25 43]

The array with Square Root Value:  [4.79583152 6.40312424 6.78232998 6.70820393 4.69041576 4.69041576
 6.         5.56776436 5.         6.55743852]

The array with rounded off squareroot values: [4.7958 6.4031 6.7823 6.7082 4.6904 4.6904 6.     5.5678 5.     6.5574]


In [16]:
array1 = np.random.randint(10,50,size = (3,3))

print("The original Array: \n",array1)
array2 = np.sqrt(array1)  
print()
print("The array with Square Root Value: \n", array2)

array3 = np.around(array2,4)
print()
print("The array with rounded off squareroot values: \n", array3)

The original Array: 
 [[47 41 38]
 [24 48 28]
 [40 15 31]]

The array with Square Root Value: 
 [[6.8556546  6.40312424 6.164414  ]
 [4.89897949 6.92820323 5.29150262]
 [6.32455532 3.87298335 5.56776436]]

The array with rounded off squareroot values: 
 [[6.8557 6.4031 6.1644]
 [4.899  6.9282 5.2915]
 [6.3246 3.873  5.5678]]


### np.cbrt

In [18]:
array1 = np.random.randint(10,50,size = (3,3))

print("The original Array: \n",array1)
array2 = np.cbrt(array1)  
print()
print("The array with Square Root Value: \n", array2)

array3 = np.around(array2,4)
print()
print("The array with rounded off cube root values: \n", array3)

The original Array: 
 [[31 41 26]
 [47 19 27]
 [23 26 18]]

The array with Square Root Value: 
 [[3.14138065 3.44821724 2.96249607]
 [3.60882608 2.66840165 3.        ]
 [2.84386698 2.96249607 2.62074139]]

The array with rounded off cube root values: 
 [[3.1414 3.4482 2.9625]
 [3.6088 2.6684 3.    ]
 [2.8439 2.9625 2.6207]]


### np.where()

In [19]:
list1 = list(np.random.randint(10,50,10))
print("The generated list: \n",list1)

The generated list: 
 [40, 21, 29, 29, 43, 40, 23, 45, 31, 14]


In [21]:
list1.index(29)

2

In [22]:
list2 = [index for index, value in enumerate(list1) if value==29]
list2

[2, 3]

In [23]:
array1 = np.array(list1)
array1

array([40, 21, 29, 29, 43, 40, 23, 45, 31, 14])

In [24]:
array2 = np.where(array1==29) ## Return a tuple containing an array with the position/index of given number
array2

(array([2, 3], dtype=int64),)

In [25]:
array2[0]

array([2, 3], dtype=int64)

In [26]:
array2 = np.where(array1 > 40)
array2

(array([4, 7], dtype=int64),)

In [27]:
array2 = np.where(array1 >= 40)
array2

(array([0, 4, 5, 7], dtype=int64),)