## Numpy Statistics

In [ ]:
1. np.mean()
2. np.median()
3. np.var()
4. np.std()
6. np.max()
7. np.min()
8. np.sum()
9. scipy.stats.mode()

In [2]:
import numpy as np

In [ ]:
### Mean median and mode are measure of  central tendancies of the data

### 1. mean()

In [3]:
list1 = [1,2,3,4,5,6,7,8,9,10]
mean_list1 = np.mean(list1)
mean_list1

5.5

In [ ]:
mean = sum of all elements in the array / length of an array

In [5]:
array1 = np.random.randint(10,99,10)
print(array1)

[13 58 63 32 41 66 96 34 97 90]


In [6]:
mean_of_array1 = np.mean(array1)
print(mean_of_array1)

59.0


### 2. Median

#### Median is defined as the middle value in the given set of numbers (data)

In [ ]:
[1 2 3 4 5 6 7 8 9]    >> Here the median is 5
[1 2 3 4 5 6 7 8 9 10] >> There are two values that fall at the center i.e. 5 and 6 therefor, for such data we take mean of
                       >> these two values >> 5+6/2 >> 5.5

In [8]:
list1 = [23,56,23,78,22,67,99,23,57,26,86]
len(list1)

11

In [10]:
list1.sort()
list1  >> Here in this list by observation we can say 56 is the median

[22, 23, 23, 23, 26, 56, 57, 67, 78, 86, 99]

In [11]:
## Checking median by numpy
np.median(list1)

56.0

### 3. Mode

In [ ]:
Most frequent value in the given set of data

In [12]:
list1 = [23,56,23,78,22,67,99,23,57,26,86]
len(list1)

11

By obeservation we can say 23 is the mode of list1
Let's check the mode with scipy library

In [13]:
from scipy.stats import mode

In [14]:
mode_of_list1 = mode(list1)

In [15]:
print(mode_of_list1)

ModeResult(mode=array([23]), count=array([3]))


In [16]:
print(mode_of_list1[0])

[23]


In [17]:
print(mode_of_list1[0][0])

23
