### 1. shape

In [2]:
import numpy as np
array1 = np.array([1,2,3,4,5,6])
array1.ndim

1

In [3]:
array2 =np.array([[1,2,3],[4,5,6],[7,8,9]])
array2.ndim

2

In [4]:
array2.shape # (row,column)

(3, 3)

In [5]:
array1.shape

(6,)

In [6]:
array1 = np.array([[1,2,3,4,5,6]])
array1.shape

(1, 6)

In [8]:
array1.T.shape

(6, 1)

In [9]:
array1.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
array1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
array1.shape

(2, 6)

In [11]:
array1D = np.array([1,2,3,4])
array1D.T

array([1, 2, 3, 4])

In [13]:
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[12,13,34],[1233,3,4]]])
array3.shape

(3, 2, 3)

In [14]:
array3 = np.array([[[1,2],[4,5]],[[7,8],[10,11]],[[12,13],[1233,3]]])
array3.shape # here the shape is (3,2,2), 3 indicates that there are three two dimensional array in  the given 3d array
             # and other two dimensions i.e. 2,2 shows that the 2D arrays have two rows and two columns

(3, 2, 2)

In [15]:
print(array3) 

[[[   1    2]
  [   4    5]]

 [[   7    8]
  [  10   11]]

 [[  12   13]
  [1233    3]]]


### 2. reshape

In [ ]:
Used to convert the shape of the array

In [16]:
array1 = np.array([1,2,3,4,5,6,7,8,9])
print("The dimension of the given array is: ", array1.ndim)
print("The shape of the given array is: ", array1.shape)

The dimension of the given array is:  1
The shape of the given array is:  (9,)


In [ ]:
rows > 9
columns > 1

columns > 9
row > 1

rows > 3
columns > 3

In [17]:
array1.reshape(9,1) # It wont change the actual array but would return a new array with the given dimensions

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [18]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
array1_1 = array1.reshape(9,1)
array1_1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [20]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
array1_2 = array1.reshape(1,9)
array1_2

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [22]:
array1_2.shape

(1, 9)

In [23]:
array1_3 = array1.reshape(3,3)
array1_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [ ]:
1*12 >> 12
12*1 >> 12
2*6  >> 12
6*2  >> 12
3*4  >> 12
4*3  >> 12

2*2*3 >> 12

In [25]:
array2_1 = array2.reshape(2,6)
print(array2_1)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [26]:
array2_2 = array2.reshape(4,3)
print(array2_2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [27]:
array2_3 = array2.reshape(2,2,3)
print(array2_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 3D to 2D

In [28]:
array3 = np.array([[[12,13],[44,23]],[[11,44],[33,66]],[[22,55],[77,44]],[[22,77],[55,88]],[[77,88],[99,22]]])

array3.shape

(5, 2, 2)

In [ ]:
5*2*2  >> 20
1*20   >> 20
2*10   >> 20
4*5    >> 20
5*4    >> 20
10*2   >> 20
20*1   >> 20

In [29]:
array3.reshape(4,5)

array([[12, 13, 44, 23, 11],
       [44, 33, 66, 22, 55],
       [77, 44, 22, 77, 55],
       [88, 77, 88, 99, 22]])

In [31]:
array3.reshape(20)

array([12, 13, 44, 23, 11, 44, 33, 66, 22, 55, 77, 44, 22, 77, 55, 88, 77,
       88, 99, 22])

### 3 nditer

In [33]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

for i in array1:
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [38]:
array2 = array1.reshape(4,3)
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
for i in array2:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [41]:
array3 = array1.reshape(2,2,3)
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
for i in array3:
    print(i)
    print()

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]



In [43]:
array2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [44]:
for i in array2:
    for j in i:
        print(j, end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [45]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
for i in array3:
    for j in i:
        for k in j:
            print(k, end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [47]:
array3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [48]:
for i in np.nditer(array3): ## np.nditer picks up individual element while running for loop over it
    print(i, end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [49]:
np.nditer(array3)