# Numpy

In [ ]:
Numpy >>>>> Numerical Python

### Applications

1. Linear Algebra
2. Statistics
3. Trignometry
4. Matrix Operations
5. Image Processing
6. Logarithms

### Numpy Properties

In [ ]:
1. It is a collection of homogenous datatype
2. Numpy is faster as compered to list
3. Numpy is written in C and C++ and partially in Python

DataType >> numpy.ndarray >> n-DimensionalArrary

The datatypes an array can have are:
    1. int
    2. float
    3. complex
    4. str

In [1]:
list1 = [1,2,3,"Data","Python", 2+3j]  # >> This is how we initiate a list

In [2]:
print(list1)

[1, 2, 3, 'Data', 'Python', (2+3j)]


In [3]:
# How to initiate numpy array
# First of all import numpy library

import numpy as np

## Write an array

array1 = np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [4]:
type(array1)

numpy.ndarray

In [5]:
array1

array([1, 2, 3, 4])

In [6]:
array1 = np.array([1,2,3,4.5]) ## Added float
print(array1)

[1.  2.  3.  4.5]


In [7]:
array1 ## If there is a single float in a numpy array, it will convert rest of the elemnts to float only, this way
       ## Numpy will keep their (element's) datatype homogeneous

array([1. , 2. , 3. , 4.5])

In [10]:
array2 = np.array([1,2,3.6,4,"5"])
print(array2) 

['1' '2' '3.6' '4' '5']


In [9]:
array2

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [14]:
array2 = np.array([1,2,3,4,6+9j])
print(array2) 

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 6.+9.j]


## Data Type Casting In Numpy

In [15]:
array1 = np.array([1,2,3,4], dtype = "int")
array1

array([1, 2, 3, 4])

In [16]:
array1 = np.array([1,2,3,4], dtype = "float")
array1

array([1., 2., 3., 4.])

In [17]:
array1 = np.array([1,2,3,4], dtype = "f")
array1

array([1., 2., 3., 4.], dtype=float32)

In [18]:
array1 = np.array([1,2,3,4], dtype = float)
array1

array([1., 2., 3., 4.])

In [19]:
array1 = np.array([1.4,2.556,3.45,4.34543], dtype = "int") ## Float to int
array1

array([1, 2, 3, 4])

In [20]:
array1 = np.array([1.4,2.556,3.45,4.34543], dtype = "i") ## Float to int
array1

array([1, 2, 3, 4], dtype=int32)

In [36]:
array1 = np.array([1634522342325365,2354325232323423,332234233646342,42323223647334234], dtype = "int") 
array1 ## Error becuase large numbers cannot be handled by simple int datatype

OverflowError: Python int too large to convert to C long

In [37]:
array1 = np.array([1634522342325365,2354325232323423,332234233646342,42323223647334234], dtype = "int64") 
array1 ## int64 can handle large numbers

array([ 1634522342325365,  2354325232323423,   332234233646342,
       42323223647334234], dtype=int64)

In [41]:
array1 = np.array([12,2,3,4], dtype = "int8")
array1

array([12,  2,  3,  4], dtype=int8)

In [42]:
array1 = np.array([12,2,3,4], dtype = "complex")
array1

array([12.+0.j,  2.+0.j,  3.+0.j,  4.+0.j])

In [43]:
array1 = np.array([12,2,3,4], dtype = complex)
array1

array([12.+0.j,  2.+0.j,  3.+0.j,  4.+0.j])

In [44]:
array1 = np.array([12+12j,2,3,4], dtype = str)
array1

array(['(12+12j)', '2', '3', '4'], dtype='<U8')

In [45]:
array1 = np.array([12,2,"3",4], dtype = complex)
array1

array([12.+0.j,  2.+0.j,  3.+0.j,  4.+0.j])

In [47]:
array1 = np.array([12,2,3+3j,4], dtype = float)
array1

TypeError: float() argument must be a string or a real number, not 'complex'

### Dimensions in Numpy array

### 1. 0-D Array

In [48]:
array1 = np.array(30)
array1

array(30)

In [49]:
array1.ndim

0

### 2. 1-D Array

In [ ]:
1D array is a collection 0 dimensional elements

In [51]:
array1 = np.array([30,11])
array1.ndim

1

In [52]:
array1 = np.array([30,11,12,343,1232,454,234,454])
array1.ndim

1

In [53]:
array1 = np.array([30])
array1.ndim

1

In [54]:
array1 = np.array(30)
array1.ndim

0

In [55]:
array1 = np.array([[30]])
array1.ndim

2

In [56]:
array1 = np.array([[[30]]])
array1.ndim

3

In [57]:
array1 = np.array([[[[30]]]])
array1.ndim

4

### 3. 2-D Array

It is a collection of multiple 1D array

In [58]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [59]:
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


In [60]:
arr1 = np.array([[1,2,3]])
arr1.ndim

2

In [64]:
array1 = np.array([[1,2,3,4],[5,6,7,8],[10,20,30,60]])
print(array1) ## This represents 3 X 4 matrics

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 60]]


In [66]:
import pandas as pd
df = pd.DataFrame(array1)
df

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2  10  20  30  60

### 4. 3D Array

In [ ]:
3D array is a collection if multiple 2D array

In [63]:
array3D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])
print(array3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### 4. 4D Array

In [ ]:
4D array is a collection if multiple 3D array

### Indexing and Slicing in Numpy Array

In [67]:
list1 = [1,2,3,4]
list1[2]

3

In [68]:
list1 = [[1,2,3,4],[5,6,7,8]]
list1[1][2]

7

In [69]:
list1 = [[[1,2,3,4],[5,6,7,8]],[[11,22,33,44],[55,66,77,88]]]
# from second 2D array I want to fetch second 1 D array

In [70]:
list1[1][1]

[55, 66, 77, 88]

In [71]:
list1[1][1][2]

77

In [72]:
array1D = np.array([1,2,3,4])
array1D[3]

4

In [73]:
array1D[2]

3

In [74]:
array2D = np.array([[1,2,3,4],[5,6,7,8]])
array2D[1]

array([5, 6, 7, 8])

In [75]:
array2D[1][3]

8

In [76]:
array3D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])
array3D[1]

C:\Users\kruna\AppData\Local\Temp\ipykernel_16608\601655383.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array3D = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15]],[[16,17,18],[19,20,21]]])


[[10, 11, 12], [13, 14, 15]]

In [79]:
array3D[1]

[[10, 11, 12], [13, 14, 15]]

In [80]:
array3D[1][1]

[13, 14, 15]

In [81]:
array3D[1][1][-1]

15

In [83]:
array1 = np.array((1,2,3,4,5,6,7))
array1

array([1, 2, 3, 4, 5, 6, 7])