In [9]:
import pandas as pd   ###<<<<< Impoting Pandas
import numpy as np

In [ ]:
PANDAS >> Python Data Analysis Library

### Two Data Structure of Pandas

In [ ]:
1. 2D - Data Structure >> DataFrame

2. 1D - Data Structure >> Series

In [2]:
dataframe = pd.read_csv("loan_data.csv")

In [3]:
dataframe

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

In [4]:
type(dataframe) ## 2-D Data Structure

pandas.core.frame.DataFrame

In [5]:
dataframe["purpose"]

0       debt_consolidation
1              credit_card
2       debt_consolidation
3       debt_consolidation
4              credit_card
               ...        
9573             all_other
9574             all_other
9575    debt_consolidation
9576      home_improvement
9577    debt_consolidation
Name: purpose, Length: 9578, dtype: object

In [6]:
type(dataframe["purpose"]) ## 1D Data Structure

pandas.core.series.Series

In [7]:
df = dataframe

## Pandas Functions

In [ ]:
1. df.columns
2. df.index
3. df.axes
4. df.dtypes
5. df.select_dtypes(include,exclude)
6. df.info
7. df.describe
8. df.shape

## Functions to access columns and rows
09. df.iloc[row_index, col_index] ## Integer Location
10. df.loc[row_label, col_label]
11. df[col_label] ## It will return single column in pandas series
12. df[col_label1, col_label2, col_label3.....col_lablen] ## This will return multiple columns
13. df[start_row_index:end_row_index] ## This will return selected rows

14. df.head() >> Starting 5 rows
15. df.tail() >> Last 5 rows

## To Read DataFrame from csv or xlsx

16. pd.read_csv()
17. pd.read_excel()

### Why do we need pandas library?

In [ ]:
1. Read the data (CSV, XLSX, JSON, SQL SERVER)
2. Data Cleaning: Missing Values, Outlier Handling
3. Exploratory Data Analysis (60%)
4. Encoding: (For training Machine Learning Algorithm)
    1. One hot encoding
    2. Label Encoding
5. Feature Selection (ML Algorithm)
6. Joining Multiple DataFrame to create an new one

### How to Create Pandas DataFrame?

In [ ]:
1. Read CSV, XLSX, JSON, SQL Server
2. Numpy array (1D or 2D)
3. Dictionary
4. List
5. Tuple
6. Series (Pandas Series)

### 1. Numpy Array

In [10]:
## 1D array
array1 = np.random.randint(10,99,10)
print(array1)

[80 15 70 82 48 24 55 30 71 47]


In [11]:
df1 = pd.DataFrame(array1)

In [12]:
df1

0
0  80
1  15
2  70
3  82
4  48
5  24
6  55
7  30
8  71
9  47

In [13]:
## 2D Array

array2 = np.random.randint(100,999,size = (10,10))
print(array2)

[[142 859 235 346 645 369 298 333 968 701]
 [957 318 151 409 886 782 185 731 530 624]
 [423 597 651 379 704 658 979 686 900 372]
 [508 104 856 446 478 540 434 626 565 137]
 [322 234 767 841 556 532 155 929 883 799]
 [123 505 263 757 558 475 165 881 246 573]
 [891 291 528 639 939 597 692 973 979 735]
 [610 156 658 368 684 411 490 361 492 540]
 [130 648 772 489 337 333 803 217 885 249]
 [230 443 549 261 651 907 305 804 145 571]]


In [15]:
df2 = pd.DataFrame(array2)
df2

0    1    2    3    4    5    6    7    8    9
0  142  859  235  346  645  369  298  333  968  701
1  957  318  151  409  886  782  185  731  530  624
2  423  597  651  379  704  658  979  686  900  372
3  508  104  856  446  478  540  434  626  565  137
4  322  234  767  841  556  532  155  929  883  799
5  123  505  263  757  558  475  165  881  246  573
6  891  291  528  639  939  597  692  973  979  735
7  610  156  658  368  684  411  490  361  492  540
8  130  648  772  489  337  333  803  217  885  249
9  230  443  549  261  651  907  305  804  145  571

In [17]:
# ## 3D Array

# array3 = np.random.randint(100,999,size = (10,10,10))
# # print(array2)

In [19]:
# df3 = pd.DataFrame(array3) #This will throw an error

In [21]:
array_zeros2 = np.zeros((10,10), dtype= int)

In [22]:
df2 = pd.DataFrame(array_zeros2)

In [23]:
df2

0  1  2  3  4  5  6  7  8  9
0  0  0  0  0  0  0  0  0  0  0
1  0  0  0  0  0  0  0  0  0  0
2  0  0  0  0  0  0  0  0  0  0
3  0  0  0  0  0  0  0  0  0  0
4  0  0  0  0  0  0  0  0  0  0
5  0  0  0  0  0  0  0  0  0  0
6  0  0  0  0  0  0  0  0  0  0
7  0  0  0  0  0  0  0  0  0  0
8  0  0  0  0  0  0  0  0  0  0
9  0  0  0  0  0  0  0  0  0  0

### 2. Create DataFrame using list

In [24]:
list1 = [1,2,3,4,5,6,7,8,9,10]
df_list = pd.DataFrame(list1)
df_list

0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [26]:
list2 = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
df_list = pd.DataFrame(list2)
df_list

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15

### 3. Creating DataFrame from Dictionary

In [27]:
dict1 = {"Name":["Rajesh","Ramesh","Suresh","Dinesh","Mahesh"],
        "Surname":["Patil","Pagare","Varma","Pawar","Pardesi"],
        "Age":[22,21,33,24,26],
        "Salary":[20000,21000,18000,22000,17000],
        "City":["Akola","Amravati","Yavatmal","Buldhana","Nagpur"]}

df_student = pd.DataFrame(dict1)
df_student

Name  Surname  Age  Salary      City
0  Rajesh    Patil   22   20000     Akola
1  Ramesh   Pagare   21   21000  Amravati
2  Suresh    Varma   33   18000  Yavatmal
3  Dinesh    Pawar   24   22000  Buldhana
4  Mahesh  Pardesi   26   17000    Nagpur

### 4. Reading CSV file

In [28]:
df_from_csv = pd.read_csv("titanic.csv")
df_from_csv

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name  Gender   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [29]:
df_from_csv2 = pd.read_csv("loan_data.csv")
df_from_csv2

credit.policy             purpose  int.rate  installment  \
0                 1  debt_consolidation    0.1189       829.10   
1                 1         credit_card    0.1071       228.22   
2                 1  debt_consolidation    0.1357       366.86   
3                 1  debt_consolidation    0.1008       162.34   
4                 1         credit_card    0.1426       102.92   
...             ...                 ...       ...          ...   
9573              0           all_other    0.1461       344.76   
9574              0           all_other    0.1253       257.70   
9575              0  debt_consolidation    0.1071        97.81   
9576              0    home_improvement    0.1600       351.58   
9577              0  debt_consolidation    0.1392       853.43   

      log.annual.inc    dti  fico  days.with.cr.line  revol.bal  revol.util  \
0          11.350407  19.48   737        5639.958333      28854        52.1   
1          11.082143  14.29   707        2760.000000      33623        76.7   
2          10.373491  11.63   682        4710.000000       3511        25.6   
3          11.350407   8.10   712        2699.958333      33667        73.2   
4          11.299732  14.97   667        4066.000000       4740        39.5   
...              ...    ...   ...                ...        ...         ...   
9573       12.180755  10.39   672       10474.000000     215372        82.1   
9574       11.141862   0.21   722        4380.000000        184         1.1   
9575       10.596635  13.09   687        3450.041667      10036        82.9   
9576       10.819778  19.18   692        1800.000000          0         3.2   
9577       11.264464  16.28   732        4740.000000      37879        57.0   

      inq.last.6mths  delinq.2yrs  pub.rec  not.fully.paid  
0                  0            0        0               0  
1                  0            0        0               0  
2                  1            0        0               0  
3                  1            0        0               0  
4                  0            1        0               0  
...              ...          ...      ...             ...  
9573               2            0        0               1  
9574               5            0        0               1  
9575               8            0        0               1  
9576               5            0        0               1  
9577               6            0        0               1  

[9578 rows x 14 columns]

### 5. Read Excel

In [30]:
df_from_xlsx = pd.read_excel("Emp_Records.xlsx")
df_from_xlsx

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]